services:
  app:
    build: .
    container_name: python_app_container
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy 

  db:
    image: postgres
    container_name: sunbiz-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/New_York
      PGTZ: America/New_York
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
